HTTP/1.1 400 Bad Request
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 172
ETag: W/"ac-DBkaw4aU9TtlmVpiAs8/RgXmKBQ"
Date: Thu, 06 Jul 2017 01:38:55 GMT
Connection: keep-alive

{"success":false,"message":"Check the form for errors.","errors":{"email":"Please provide a correct email address.","password":"Password must have at least 8 characters."}}