HTTP/1.1 400 Bad Request
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 57
ETag: W/"39-+cJ/8lq+3tNnhZXQnXlnm0swmns"
Date: Thu, 06 Jul 2017 01:42:01 GMT
Connection: keep-alive

{"success":false,"message":"Incorrect email or password"}